name: wigo
description: Wherigo Player written in Flutter

version: 1.0.0+1

publish_to: none

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^0.6.9
  bloc: ^6.1.1
  built_collection: ^4.3.2
  built_value: ^7.1.0
  cupertino_icons: ^1.0.0
  equatable: ^1.2.5
  flutter_bloc: ^6.1.1
  freewig:
    git: git@github.com:mars3142/freewig.git
  get_it: ^5.0.4
  injectable: ^1.0.7
  maverick:
    git: git@github.com:mars3142/maverick.git
  path_provider: ^1.6.27

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^0.6.9
  build_runner: ^1.10.2
  built_value_generator: ^7.1.0
  effective_dart: ^1.3.0
  injectable_generator: ^1.0.5

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - gwc/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
