name: Build Apps

on:
  push:
    branches:
      - master

jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Flutter action
        uses: subosito/flutter-action@v1
        with:
          channel: 'beta'

      - name: Flutter test
        run: flutter test

  build_android:
    needs: tests
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'

      - run: flutter pub get

      - run: flutter build apk --release

  build_ios:
    needs: tests
    name: Build for iOS
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'

      - run: flutter pub get

      - run: flutter build ios --release --no-codesign
