name: Build Apps

on:
  push:
    branches:
      - master

jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest

    container:
      image: cirrusci/flutter:latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Flutter action
        uses: subosito/flutter-action@v1.4.0
        with:
          flutter-version: 1.22.1

      - name: Flutter test
        run: flutter test

  build_android:
    needs: tests
    name: Build for Android
    runs-on: ubuntu-latest

    container:
      image: cirrusci/flutter:latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

  build_ios:
    needs: tests
    name: Build for iOS
    runs-on: macos-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
